version: '3'

services:
  codeigniter:
    build:
      context: ./codeigniter
    ports:
      - "80:80"
    depends_on:
      - fuseki
    healthcheck:
      test: ["CMD", "curl", "-f", "http://fuseki:3030/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    command: ["php", "-S", "0.0.0.0:80"]

  fuseki:
    build:
      context: ./fuseki
    ports:
      - "3030:3030"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/health"]
      interval: 30s
      timeout: 3s
      retries: 3
